Repository one-acre-fund/oaf-ph-ee-operations-web, pull requests merged in 2023-09, with the labels that each got.

#12 Setup azure pipeline - SER-1971
  azure-pipelines.yml
Labels: size/M

#13 [Snyk] Security upgrade nginx from 1.19.3 to 1.25.1
  Dockerfile
Labels: size/XS

#10 [Snyk] Upgrade angular-archwizard from 5.0.0 to 5.0.1
  package.json
Labels: size/XS

#11 [Snyk] Upgrade: @angular/animations, @angular/common, @angular/compiler, @angular/core, @angular/forms, @angular/platform-browser, @angular/platform-browser-dynamic, @angular/router, @angular/service-worker
  package.json
Labels: size/S

#9 [Snyk] Upgrade zone.js from 0.11.8 to 0.13.1
  package.json
Labels: size/XS

#8 [Snyk] Upgrade @fortawesome/angular-fontawesome from 0.10.1 to 0.13.0
  package.json
Labels: size/XS

#4 [Snyk] Upgrade core-js from 2.5.0 to 2.6.12
  package.json
Labels: size/XS

#7 [Snyk] Upgrade @fortawesome/free-solid-svg-icons from 6.0.0 to 6.4.2
  package.json
Labels: size/XS

#15 Fix errors that occur when exporting transactions as csv - SER-1926
  RELEASE_NOTES.md
  src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.html
  src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.ts
  src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.html
  src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.ts
  src/app/payment-hub/request-to-pay/service/request-to-pay.service.ts
Labels: size/L

#6 [Snyk] Upgrade lodash from 4.17.13 to 4.17.21
  package.json
Labels: size/XS

#5 [Snyk] Upgrade @swimlane/ngx-charts from 20.0.1 to 20.4.1
  package.json
Labels: size/XS
