Repository one-acre-fund/oaf-ph-ee-operations-web, pull requests merged in 2023-10, with the labels that each got.

#18 Rename master to main in CI file
  azure-pipelines.yml
Labels: size/S

#19 Undo snyk recommended upgrades - SER-2059
  Dockerfile
  azure-pipelines.yml
  package.json
Labels: size/M

#17 Merge develop into main
  RELEASE_NOTES.md
  src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.html
  src/app/payment-hub/request-to-pay/incoming-request-export/incoming-request-export.component.ts
  src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.html
  src/app/payment-hub/request-to-pay/incoming-request-to-pay/incoming-request-to-pay.component.ts
  src/app/payment-hub/request-to-pay/service/request-to-pay.service.ts
  src/app/payment-hub/transactions/incoming/incoming-transactions.component.html
  src/app/payment-hub/transactions/incoming/incoming-transactions.component.ts
  src/app/payment-hub/transactions/outgoing/outgoing-transactions.component.html
  src/app/payment-hub/transactions/outgoing/outgoing-transactions.component.ts
Labels: size/L
